const arrow = `<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4" /></svg>`;
const mark = (light = false) => `<span class="mark ${light ? 'mark-light' : ''}" aria-hidden="true"><svg viewBox="0 0 42 42"><path d="M21 3 36 9v10c0 9.5-6.3 16.8-15 20C12.3 35.8 6 28.5 6 19V9l15-6Z"/><path d="m13.5 23 7.5-12 7.5 12M16.4 19h9.2" /></svg></span>`;
const benefits = [
  ['01','See your AI landscape','Create a living inventory of every AI system, owner, vendor, and use case across your organisation.'],
  ['02','Understand real risk','Turn complex regulations and technical signals into clear, prioritised actions for every team.'],
  ['03','Prove responsible practice','Keep audit-ready evidence in one place and show customers, boards, and regulators how AI is governed.']
];
const steps = [['Discover','Map systems, stakeholders, and obligations in days—not months.'],['Assess','Apply a consistent risk framework to every AI use case.'],['Act','Give owners clear tasks, controls, and expert guidance.'],['Assure','Monitor progress and export the evidence you need.']];
const faqs = [['Who is Aegis for?','Aegis is designed for growing organisations adopting AI across teams—especially leaders responsible for risk, compliance, data, technology, and innovation.'],['Do we need an AI policy already?','Not at all. We can help you start from first principles or translate an existing policy into a practical, measurable governance programme.'],['How quickly can we get started?','A focused discovery can begin immediately. Most teams establish their initial inventory and risk baseline within the first few weeks.']];

document.querySelector('#root').innerHTML = `<main>
<div class="announcement">Aegis is now accepting founding partners <button data-scroll="contact">Learn more ${arrow}</button></div>
<nav class="nav shell" aria-label="Main navigation"><button class="brand" data-scroll="top" aria-label="Aegis home">${mark()}<span>AEGIS</span><small>by Klein Consulting</small></button><div class="nav-links"><button data-scroll="platform">Platform</button><button data-scroll="approach">Our approach</button><button data-scroll="insights">Insights</button><button class="nav-cta" data-scroll="contact">Book a conversation ${arrow}</button></div><button class="menu" aria-label="Toggle menu" aria-expanded="false"><span></span><span></span></button></nav>
<section class="hero shell" id="top"><div class="hero-copy"><div class="eyebrow"><i></i> AI governance, made actionable</div><h1>Move forward with AI.<br><em>Without looking back.</em></h1><p>Aegis gives ambitious teams the clarity, controls, and confidence to adopt AI responsibly—without slowing innovation down.</p><div class="hero-actions"><button class="button dark" data-scroll="contact">Explore Aegis ${arrow}</button><button class="text-button" data-scroll="platform">See how it works <span>↓</span></button></div></div>
<div class="hero-visual" aria-label="Aegis risk overview interface preview"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="dash-card"><div class="dash-top"><div>${mark(true)}<span>AEGIS</span></div><span class="live"><i></i> LIVE</span></div><p class="mono">ORGANISATION OVERVIEW</p><div class="score-row"><div><small>Governance readiness</small><strong>82<span>/100</span></strong></div><div class="score-ring"><b>82</b></div></div><div class="status-grid"><div><i class="green"></i><strong>24</strong><small>Low risk</small></div><div><i class="amber"></i><strong>08</strong><small>Review</small></div><div><i class="red"></i><strong>02</strong><small>Action</small></div></div><div class="dash-foot"><span>Last assessment</span><strong>Updated today</strong></div></div><div class="signal-card"><span class="signal-icon">✓</span><div><small>CONTROL VERIFIED</small><strong>Human oversight</strong></div></div></div>
<div class="trust"><span>Built for teams navigating</span><div><b>EU AI ACT</b><b>ISO 42001</b><b>NIST AI RMF</b><b>GDPR</b></div></div></section>
<section class="problem" id="platform"><div class="shell"><div class="section-label">THE CHALLENGE</div><div class="problem-intro"><h2>AI moves fast.<br>Governance usually doesn't.</h2><p>Policies sit in documents. Risk lives in spreadsheets. Ownership is unclear. Aegis brings it all together—so responsible AI becomes how you work, not extra work.</p></div><div class="benefits">${benefits.map(b=>`<article><span>${b[0]}</span><div class="benefit-icon"><span></span><span></span><span></span></div><h3>${b[1]}</h3><p>${b[2]}</p><button data-scroll="approach" aria-label="Learn about ${b[1]}">${arrow}</button></article>`).join('')}</div></div></section>
<section class="approach shell" id="approach"><div class="approach-copy"><div class="section-label">ONE CONNECTED SYSTEM</div><h2>From uncertainty<br>to <em>assurance.</em></h2><p>Aegis combines thoughtful technology with hands-on expertise. The platform creates structure; our consultants help you make the decisions that matter.</p><button class="button outline" data-scroll="contact">Our approach ${arrow}</button></div><div class="steps">${steps.map((s,i)=>`<div class="step"><span>0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div><b>${i===3?'✓':'→'}</b></div>`).join('')}</div></section>
<section class="quote-band" id="insights"><div class="shell">${mark(true)}<blockquote>“Governance shouldn't be the brake on innovation. Done well, it's what gives people the confidence to accelerate.”</blockquote><div><span></span><p><strong>Klein Consulting</strong><br>Responsible AI, made practical</p></div></div></section>
<section class="faq shell"><div><div class="section-label">QUESTIONS, ANSWERED</div><h2>A clearer way<br>forward.</h2></div><div class="faq-list">${faqs.map((f,i)=>`<div class="faq-item ${i===0?'active':''}"><button aria-expanded="${i===0}"><span>${f[0]}</span><b>${i===0?'−':'+'}</b></button><div class="answer"><p>${f[1]}</p></div></div>`).join('')}</div></section>
<section class="contact" id="contact"><div class="shell contact-grid"><div><div class="section-label light-label">START A CONVERSATION</div><h2>Ready to move<br>with <em>confidence?</em></h2><p>Tell us where you are on your AI journey. We'll show you how Aegis can help you take the next step.</p></div><form><label>Name<input required placeholder="Your name"></label><label>Work email<input required type="email" placeholder="you@company.com"></label><label>What would you like help with?<select required><option value="" selected disabled>Select an area</option><option>AI governance strategy</option><option>AI risk assessment</option><option>EU AI Act readiness</option><option>Platform demonstration</option></select></label><button class="button lime" type="submit">Book a conversation ${arrow}</button><small>By submitting, you agree to our privacy policy.</small></form></div></section>
<footer class="footer"><div class="shell"><div class="footer-top"><div class="brand footer-brand">${mark(true)}<span>AEGIS</span><small>by Klein Consulting</small></div><p>Practical governance for<br>responsible AI.</p><div><button data-scroll="platform">Platform</button><button data-scroll="approach">Approach</button><button data-scroll="contact">Contact</button></div></div><div class="footer-bottom"><span>© 2026 Klein Consulting. All rights reserved.</span><div><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div></footer></main>`;

const nav = document.querySelector('.nav-links');
const menu = document.querySelector('.menu');
menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('[data-scroll]').forEach(button => button.addEventListener('click', () => { document.getElementById(button.dataset.scroll)?.scrollIntoView({behavior:'smooth'}); nav.classList.remove('open'); menu.setAttribute('aria-expanded','false'); }));
document.querySelectorAll('.faq-item').forEach(item => item.querySelector('button').addEventListener('click', () => { const wasOpen=item.classList.contains('active'); document.querySelectorAll('.faq-item').forEach(other=>{other.classList.remove('active');other.querySelector('button').setAttribute('aria-expanded','false');other.querySelector('b').textContent='+'}); if(!wasOpen){item.classList.add('active');item.querySelector('button').setAttribute('aria-expanded','true');item.querySelector('b').textContent='−'}}));
document.querySelector('form').addEventListener('submit', e => {e.preventDefault(); e.currentTarget.outerHTML='<div class="thanks"><span>✓</span><h3>Thanks for reaching out.</h3><p>We’ll be in touch shortly to start the conversation.</p></div>';});
